version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bootdb
  stockManager:
    image: lucasvilela/stock-manager
    container_name: stock-manager
    networks:
      - compose-bridge
  stockQuotes:
    image: lucascz37/stock-quotes
    container_name: stock-quotes
    networks:
      - compose-bridge
    ports:
      - "8081:8081"
    depends_on:
      - stockManager
      - mysql

networks:
  compose-bridge:
    driver: bridge